### ISSUE TITLE
non-default config projects are not read

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/dccmonitor#128]
Only the default config.yml settings are being read, despite setting R_CONFIG_ACTIVE to "amp-ad".

**Comment by danlu1** [comment]
For my usecase, this issue happened when I called[ dccvalidator::gather_template_ids](https://github.com/Sage-Bionetworks/dccmonitor/blob/master/R/validate-by-study.R#:~:text=manifest%20%3D-,dccvalidator%3A%3Agather_template_ids,-(%22manifest%22)%2C). The [get_golem_config](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/app-config.R) in [gather_template_ids](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/df-helpers.R#:~:text=gather_template_ids%20%3C%2D%20function(type,%7D) refers to the config file of released dccvalidator app. I guess the reason is that the app_sys() reset the app's config file from dccmonitor to dccvalidator. See the following screenshots.

**Comment by danlu1** [comment]
This screenshot shows that in the config::get() used by get_golem_config, **file** value has been updated to dccvalidator/config.yml instead of the one in dccmonitor. <img width="1440" alt="Screen Shot 2022-03-26 at 2 15 21 PM" src="https://user-images.githubusercontent.com/90745557/160447875-115caa83-8385-4174-b64f-b52db6a21ce0.png">

This shows the loaded config files. It only includes the config of the released version of dccvalidator (not includes the most recent changes in github repo)
<img width="1440" alt="Screen Shot 2022-03-26 at 2 15 44 PM" src="https://user-images.githubusercontent.com/90745557/160448489-e7249633-f518-4c64-8323-273bb5cc26de.png">

Take pec for example. 
<img width="916" alt="Screen Shot 2022-03-28 at 9 55 19 AM" src="https://user-images.githubusercontent.com/90745557/160449257-f690751d-725b-44bb-9d1f-1f2cf23d4a43.png">

**Comment by danlu1** [comment]
I believe we have 3 approaches to solve this problem. 1. (quickest fix) save the df_helpers script in dccmonitor repo and call gather_template_ids directly. By doing this, we can make sure the app calls correct config file and not rely on the synchrony of config files in dccvalidator and dccmonitor. 2. synchronize the config files for both apps. 3. modify the [app_sys](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/app-config.R#:~:text=app_sys%20%3C%2D%20function(...)%20%7B,%7D) and allow it to refer to the current app instead of a predefined app.

**Comment by ychae** [comment]
Will need to look into to see how much time it will take to solve - 1 day timebox
AC: app reads config values from non-default projects

**Comment by afwillia** [comment]
I think updating the app_sys function like @danlu1 suggested will be the most reliable way forward. I can push a fix this sprint @ychae

**Comment by danlu1** [comment]
The same issue happened when running check_cols_complete from dccvalidator::check_all().

The get_golem_config get dccvalidator default config. The default required column (individualID) in individual file has been checked instead of what listed in the config for 1kD. 

<img width="1440" alt="Screen Shot 2022-03-29 at 10 34 59 PM" src="https://user-images.githubusercontent.com/90745557/160758771-aee4a2b6-984e-4e0b-8b4c-0b7b6a203172.png">
 
<img width="308" alt="Screen Shot 2022-03-29 at 10 42 51 PM" src="https://user-images.githubusercontent.com/90745557/160759531-3b3b349a-7cce-4c59-afab-fb1455a9ea90.png">

The dccmonitor is not generating the error that generated by dccvalidator: There is missing data in some columns that are required to be complete in the individual metadata.

<img width="1440" alt="Screen Shot 2022-03-29 at 10 33 43 PM" src="https://user-images.githubusercontent.com/90745557/160759303-3c5cefd8-0bb6-4a52-b444-fb1f60c3cbca.png">

<img width="1440" alt="Screen Shot 2022-03-29 at 10 33 33 PM" src="https://user-images.githubusercontent.com/90745557/160759319-40dc07b3-49e4-49c6-a7bb-0b1ab0747e8c.png">

**Comment by afwillia** [comment]
@ychae on second thought after trying to update the app_sys() function, this will require a bit more thought. @danlu1 Syncing the dccvalidator config file so it matches dccmonitor should fix this issue.
