### ISSUE TITLE
Bug with file details tab

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccmonitor#48]
The app hosted on the shiny server is down - there are no output logs to help debug :)

I can run locally, however I return this error when I click on the Data Summary > File Details summary for any study. 
```
Warning: Error in : Can't find columns `variable`, `type`, `missing`, `complete`, `n`, … (and 4 more) in `.data`.
  106: <Anonymous>
```
The app worked fine one minute and then when I tried to reload 2 minutes later, it was down. I cannot find anything on the back end (in terms of dccvalidator uploads) that changed.

**Comment by karawoo** [comment]
What version of skimr are you using? I think that might be the issue that you are seeing locally.

**Comment by karawoo** [comment]
Also when you say the app is down, what exactly are you seeing? Is it the "disconnected from server" error? If you try logging out and back in to synapse, does that change anything? We've been seeing an increasing number of issues due to invalid session tokens; I'm not sure why this is happening, but it's possible that's the issue.

**Comment by kelshmo** [comment]
skimr 2.0.2 

Yes, disconnected from the server error. I tried logging in and out to synapse and that did not resolve the "disconnected from server" error.

**Comment by karawoo** [comment]
If you restore to the version of skimr in the lockfile it should solve that local problem. Not sure what's causing the error on the server. Where is dccmonitor for PEC hosted, can you send me the URL?

**Comment by kelshmo** [comment]
Pulling in updates from `master` fixed the problem 🤷‍♀ !
