### ISSUE TITLE
Store to Synapse instead of download

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccmonitor#61]
Is it possible to store the Annotations tab output to a designated Synapse folder instead of download a file? This would be preferred so data can be manipulated primarily programmatically.

I know this gets into tricky session token issues.

**Comment by Aryllen** [comment]
I don't see a problem with uploading it to a Synapse folder, but I'm not sure I understand how that makes it any more programmatic. I'd be happy to discuss with you what the change would look like.

**Comment by kelshmo** [comment]
I guess I am thinking about two components to the process: 1) Getting the merged data from the dccmonitor into sci-comp (by downloading it) may be technically challenging. 2) if the data is deposited to a Synapse folder we may be able to further automate some subsequent steps.

**Comment by Aryllen** [comment]
Discussed this with @kelshmo today.

Create another folder called dccmonitor in the validation project and a config parameter for this folder ID. For each user, create a subfolder that the annotations csv will be uploaded to, similar to how this is done for dccvalidator uploads. This reduces the risk of different curators overwriting the same file if they give it the same name. Additionally, since the app isn't making up new, unique names, this reduces the chance of creating superfluous files. The csv should be uploaded with the study name as an annotation.
