### ISSUE TITLE
Download Error with Validate

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccmonitor#78]
When trying to validate the [3Dchromatin study](https://shinypro.synapse.org/users/kmontgomery/dccmonitor/), I return this error:

` Error: Couldn't download metadata template. Make sure you are logged in to Synapse and that `synID` is a valid synapse ID.FALSE `

The other studies appear to be working OK.

**Comment by kelshmo** [comment]
I'm trying to reverse engineer this [dccvalidator error](https://github.com/Sage-Bionetworks/dccvalidator/blob/d683406db5605cb12812a3d4b0e9b6f2faaa2e4a/R/check-col-names.R#L157-L163).

**Comment by Aryllen** [comment]
That study is using a HI-C assay template. The config for dccmonitor does not have this. The dccvalidator and dccmonitor configs need to match in the templates section or there will be errors.

I also noticed an error in the individual templates. https://github.com/Sage-Bionetworks/dccmonitor/blob/40c7c4c6ad718c0eda9fd2fec1adf00f9505a986/config.yml#L88
This should say `animal model:`, not just `animal` since that is what the label is under `species`. That should not be causing a problem here, though. I think the lack of a HI-C assay template in the dccmonitor config is problem.
